# Generated by Django 5.2.1 on 2025-06-02 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PredictionRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("player_1", models.CharField(max_length=100)),
                ("player_2", models.CharField(max_length=100)),
                ("player_1_rank", models.IntegerField()),
                ("player_2_rank", models.IntegerField()),
                ("surface", models.CharField(max_length=20)),
                ("tourney_date", models.DateField()),
                ("predicted_winner", models.CharField(max_length=100)),
                ("request_time", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
