# Generated by Django 5.2.1 on 2026-06-03 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0002_predictionrequest_tour_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='predictionrequest',
            name='confidence',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='predictionrequest',
            name='model_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
